version: '3'

services:

  nginx_wp:
      image: nginx:latest
      build: ./docker/nginx
      ports:
          - "8080:80" # if you want use other port, change in (example 8888:80)
      volumes:
          - ./http:/var/www/html
          - ./docker/nginx/wordpress.conf:/etc/nginx/conf.d/default.conf
      links:
          - php
  php:
      image: php:7-fpm
      volumes:
          - ./http:/var/www/html
  wordpress:
     image: wordpress:latest
     volumes:
        - ./http:/var/www/html
     environment:
       WORDPRESS_DB_HOST: wp
       WORDPRESS_DB_NAME: wp
       WORDPRESS_DB_PASSWORD: wp
       WORDPRESS_DB_USER: wp
     depends_on:
        - nginx_wp
        - mariadb
  mariadb:
     image: mariadb:latest
     volumes:
       - ./DB:/docker-entrypoint-initdb.d
     environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
     ports:
       - 3307:3306
volumes:
     data-volume:
