version: '3'

services:

  nginx_wp:
    build: ./docker/nginx
    ports:
      - 8989:80 # if you want use other port, change in (example 8888:80)
    volumes:
      - ./http:/var/www/html
      - ./docker/wordpress/wp-config.local.php:/var/www/wp-config.local.php
      - ./docker/nginx/wordpress.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx
    links:
      - php
      - mariadb
    environment:
      DB_HOST: mariadb
  php:
    build: ./docker/php
    volumes:
      - ./http:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_USER: wp
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    volumes:
      - ./DB:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
     PMA_HOST: mariadb
     PMA_USER: wp
     PMA_PASSWORD: wp
     PHP_UPLOAD_MAX_FILESIZE: 1G
     PHP_MAX_INPUT_VARS: 1G
    ports:
      - 8990:80
    depends_on:
      - mariadb
volumes:
    data-volume:
