version: '3'

services:

  nginx_wp:
    image: nginx:latest
    build: ./docker/nginx
    ports:
      - 8080:80 # if you want use other port, change in (example 8888:80)
    volumes:
      - ./web:/var/www/html
      - ./docker/nginx/wordpress.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx
    links:
      - php
      - mariadb
    environment:
      DB_HOST: mariadb
  php:
    image: php:7-fpm
    build: ./docker/php
    volumes:
      - ./web:/var/www/html
      - ./docker/php/config/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
  wordpress:
    image: wordpress:latest
    volumes:
      - ./web:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_USER: wp
    depends_on:
      - nginx_wp
      - mariadb
  mariadb:
    image: mariadb:latest
    volumes:
      - ./DB:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
     PMA_HOST: mariadb
     PMA_USER: wp
     PMA_PASSWORD: wp
     PHP_UPLOAD_MAX_FILESIZE: 1G
     PHP_MAX_INPUT_VARS: 1G
    ports:
    - 8001:80
volumes:
    data-volume:
